# -*- coding: utf-8 -*-
"""cancer_diagnosis_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6NnFeoB2WNaDGD0trBt6QD0miRpRmQf
"""

!pip install langchain neo4j transformers langchain_community
!pip install transformers
!pip install transformers datasets accelerate torch


from transformers import pipeline
import pandas as pd

from transformers import pipeline

# Load the LLM model (FLAN-T5 for text generation)
llm = pipeline("text2text-generation", model="google/flan-t5-xl")

def predict_with_llm(patient_data: dict):

    prompt = f"""
    You are a medical classification assistant. Your task is to determine:
    1. The 'cancer type' of the patient.
    2. Whether they are 'newly diagnosed' or 'relapsed'.

    Provide your answer in the following format:
    Cancer Type: <cancer_type>
    Diagnosis Status: <newly diagnosed/relapsed>

    Patient Information:
    - Cancer Type: {patient_data['cancer_type']}
    - Previous Cancer History: {patient_data['previous_cancer_history']}

    Provide the answer in the exact format specified.
    """

    # Generate response from LLM
    response = llm(prompt, max_length=50, num_return_sequences=1)[0]['generated_text'].strip()

    return response

# Example test case
test_patient = {
    "age": 45,
    "gender": "Female",
    "cancer_type": "Breast Cancer",
    "organ_function_status": "Normal",
    "presence_of_metastases": "f",
    "clinical_pathological_risk_features": "Hormone receptor negative",
    "comorbidities": "Hypertension",
    "previous_cancer_history": "lots",
    "pregnancy_breastfeeding_status": "Not Applicable",
    "compliance_with_study_protocol": "t",
    "genetic_mutations": "TP53",
    "ecog_performance_status": 1,
    "tumor_characteristics": "Size: 2cm, Grade: 2, ER/PR: Positive, HER2: Negative",
    "treatment_history": "Adjuvant Chemotherapy, Radiotherapy"
}

# Run prediction
llm_prediction = predict_with_llm(test_patient)
print(llm_prediction)